# Generated by Django 5.0.3 on 2024-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('U', 'User'), ('V', 'Vendor'), ('A', 'Admin')], default='U', max_length=1),
        ),
    ]
